// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,json_types=true"
// @generated from file PublicSpotKlineV3Api.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PublicSpotKlineV3Api.proto.
 */
export const file_PublicSpotKlineV3Api: GenFile = /*@__PURE__*/
  fileDesc("ChpQdWJsaWNTcG90S2xpbmVWM0FwaS5wcm90byLHAQoUUHVibGljU3BvdEtsaW5lVjNBcGkSEAoIaW50ZXJ2YWwYASABKAkSEwoLd2luZG93U3RhcnQYAiABKAMSFAoMb3BlbmluZ1ByaWNlGAMgASgJEhQKDGNsb3NpbmdQcmljZRgEIAEoCRIUCgxoaWdoZXN0UHJpY2UYBSABKAkSEwoLbG93ZXN0UHJpY2UYBiABKAkSDgoGdm9sdW1lGAcgASgJEg4KBmFtb3VudBgIIAEoCRIRCgl3aW5kb3dFbmQYCSABKANCPQocY29tLm14Yy5wdXNoLmNvbW1vbi5wcm90b2J1ZkIZUHVibGljU3BvdEtsaW5lVjNBcGlQcm90b0gBUAFiBnByb3RvMw");

/**
 * @generated from message PublicSpotKlineV3Api
 */
export type PublicSpotKlineV3Api = Message<"PublicSpotKlineV3Api"> & {
  /**
   * K线周期(Min1,Min5,Min15,Min30,Min60,Hour4,Hour8,Day1,Week1,Month1)
   *
   * @generated from field: string interval = 1;
   */
  interval: string;

  /**
   * 窗口开始时间戳(秒时间戳)
   *
   * @generated from field: int64 windowStart = 2;
   */
  windowStart: bigint;

  /**
   * 开盘价
   *
   * @generated from field: string openingPrice = 3;
   */
  openingPrice: string;

  /**
   * 收盘价
   *
   * @generated from field: string closingPrice = 4;
   */
  closingPrice: string;

  /**
   * 最高价
   *
   * @generated from field: string highestPrice = 5;
   */
  highestPrice: string;

  /**
   * 最低价
   *
   * @generated from field: string lowestPrice = 6;
   */
  lowestPrice: string;

  /**
   * 成交量
   *
   * @generated from field: string volume = 7;
   */
  volume: string;

  /**
   * 成交额
   *
   * @generated from field: string amount = 8;
   */
  amount: string;

  /**
   * 窗口结束时间戳(秒时间戳)
   *
   * @generated from field: int64 windowEnd = 9;
   */
  windowEnd: bigint;
};

/**
 * @generated from message PublicSpotKlineV3Api
 */
export type PublicSpotKlineV3ApiJson = {
  /**
   * K线周期(Min1,Min5,Min15,Min30,Min60,Hour4,Hour8,Day1,Week1,Month1)
   *
   * @generated from field: string interval = 1;
   */
  interval?: string;

  /**
   * 窗口开始时间戳(秒时间戳)
   *
   * @generated from field: int64 windowStart = 2;
   */
  windowStart?: string;

  /**
   * 开盘价
   *
   * @generated from field: string openingPrice = 3;
   */
  openingPrice?: string;

  /**
   * 收盘价
   *
   * @generated from field: string closingPrice = 4;
   */
  closingPrice?: string;

  /**
   * 最高价
   *
   * @generated from field: string highestPrice = 5;
   */
  highestPrice?: string;

  /**
   * 最低价
   *
   * @generated from field: string lowestPrice = 6;
   */
  lowestPrice?: string;

  /**
   * 成交量
   *
   * @generated from field: string volume = 7;
   */
  volume?: string;

  /**
   * 成交额
   *
   * @generated from field: string amount = 8;
   */
  amount?: string;

  /**
   * 窗口结束时间戳(秒时间戳)
   *
   * @generated from field: int64 windowEnd = 9;
   */
  windowEnd?: string;
};

/**
 * Describes the message PublicSpotKlineV3Api.
 * Use `create(PublicSpotKlineV3ApiSchema)` to create a new message.
 */
export const PublicSpotKlineV3ApiSchema: GenMessage<PublicSpotKlineV3Api, PublicSpotKlineV3ApiJson> = /*@__PURE__*/
  messageDesc(file_PublicSpotKlineV3Api, 0);

