// spot@public.miniTickers.v3.api

// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,json_types=true"
// @generated from file PublicMiniTickersV3Api.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { PublicMiniTickerV3Api, PublicMiniTickerV3ApiJson } from "./PublicMiniTickerV3Api_pb";
import { file_PublicMiniTickerV3Api } from "./PublicMiniTickerV3Api_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PublicMiniTickersV3Api.proto.
 */
export const file_PublicMiniTickersV3Api: GenFile = /*@__PURE__*/
  fileDesc("ChxQdWJsaWNNaW5pVGlja2Vyc1YzQXBpLnByb3RvIj8KFlB1YmxpY01pbmlUaWNrZXJzVjNBcGkSJQoFaXRlbXMYASADKAsyFi5QdWJsaWNNaW5pVGlja2VyVjNBcGlCPwocY29tLm14Yy5wdXNoLmNvbW1vbi5wcm90b2J1ZkIbUHVibGljTWluaVRpY2tlcnNWM0FwaVByb3RvSAFQAWIGcHJvdG8z", [file_PublicMiniTickerV3Api]);

/**
 * @generated from message PublicMiniTickersV3Api
 */
export type PublicMiniTickersV3Api = Message<"PublicMiniTickersV3Api"> & {
  /**
   * @generated from field: repeated PublicMiniTickerV3Api items = 1;
   */
  items: PublicMiniTickerV3Api[];
};

/**
 * @generated from message PublicMiniTickersV3Api
 */
export type PublicMiniTickersV3ApiJson = {
  /**
   * @generated from field: repeated PublicMiniTickerV3Api items = 1;
   */
  items?: PublicMiniTickerV3ApiJson[];
};

/**
 * Describes the message PublicMiniTickersV3Api.
 * Use `create(PublicMiniTickersV3ApiSchema)` to create a new message.
 */
export const PublicMiniTickersV3ApiSchema: GenMessage<PublicMiniTickersV3Api, PublicMiniTickersV3ApiJson> = /*@__PURE__*/
  messageDesc(file_PublicMiniTickersV3Api, 0);

