// spot@public.increase.depth.v3.api.pb

// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,json_types=true"
// @generated from file PublicIncreaseDepthsV3Api.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PublicIncreaseDepthsV3Api.proto.
 */
export const file_PublicIncreaseDepthsV3Api: GenFile = /*@__PURE__*/
  fileDesc("Ch9QdWJsaWNJbmNyZWFzZURlcHRoc1YzQXBpLnByb3RvIpkBChlQdWJsaWNJbmNyZWFzZURlcHRoc1YzQXBpEisKBGFza3MYASADKAsyHS5QdWJsaWNJbmNyZWFzZURlcHRoVjNBcGlJdGVtEisKBGJpZHMYAiADKAsyHS5QdWJsaWNJbmNyZWFzZURlcHRoVjNBcGlJdGVtEhEKCWV2ZW50VHlwZRgDIAEoCRIPCgd2ZXJzaW9uGAQgASgJIj8KHFB1YmxpY0luY3JlYXNlRGVwdGhWM0FwaUl0ZW0SDQoFcHJpY2UYASABKAkSEAoIcXVhbnRpdHkYAiABKAlCQgocY29tLm14Yy5wdXNoLmNvbW1vbi5wcm90b2J1ZkIeUHVibGljSW5jcmVhc2VEZXB0aHNWM0FwaVByb3RvSAFQAWIGcHJvdG8z");

/**
 * @generated from message PublicIncreaseDepthsV3Api
 */
export type PublicIncreaseDepthsV3Api = Message<"PublicIncreaseDepthsV3Api"> & {
  /**
   * @generated from field: repeated PublicIncreaseDepthV3ApiItem asks = 1;
   */
  asks: PublicIncreaseDepthV3ApiItem[];

  /**
   * @generated from field: repeated PublicIncreaseDepthV3ApiItem bids = 2;
   */
  bids: PublicIncreaseDepthV3ApiItem[];

  /**
   * @generated from field: string eventType = 3;
   */
  eventType: string;

  /**
   * @generated from field: string version = 4;
   */
  version: string;
};

/**
 * @generated from message PublicIncreaseDepthsV3Api
 */
export type PublicIncreaseDepthsV3ApiJson = {
  /**
   * @generated from field: repeated PublicIncreaseDepthV3ApiItem asks = 1;
   */
  asks?: PublicIncreaseDepthV3ApiItemJson[];

  /**
   * @generated from field: repeated PublicIncreaseDepthV3ApiItem bids = 2;
   */
  bids?: PublicIncreaseDepthV3ApiItemJson[];

  /**
   * @generated from field: string eventType = 3;
   */
  eventType?: string;

  /**
   * @generated from field: string version = 4;
   */
  version?: string;
};

/**
 * Describes the message PublicIncreaseDepthsV3Api.
 * Use `create(PublicIncreaseDepthsV3ApiSchema)` to create a new message.
 */
export const PublicIncreaseDepthsV3ApiSchema: GenMessage<PublicIncreaseDepthsV3Api, PublicIncreaseDepthsV3ApiJson> = /*@__PURE__*/
  messageDesc(file_PublicIncreaseDepthsV3Api, 0);

/**
 * @generated from message PublicIncreaseDepthV3ApiItem
 */
export type PublicIncreaseDepthV3ApiItem = Message<"PublicIncreaseDepthV3ApiItem"> & {
  /**
   * @generated from field: string price = 1;
   */
  price: string;

  /**
   * @generated from field: string quantity = 2;
   */
  quantity: string;
};

/**
 * @generated from message PublicIncreaseDepthV3ApiItem
 */
export type PublicIncreaseDepthV3ApiItemJson = {
  /**
   * @generated from field: string price = 1;
   */
  price?: string;

  /**
   * @generated from field: string quantity = 2;
   */
  quantity?: string;
};

/**
 * Describes the message PublicIncreaseDepthV3ApiItem.
 * Use `create(PublicIncreaseDepthV3ApiItemSchema)` to create a new message.
 */
export const PublicIncreaseDepthV3ApiItemSchema: GenMessage<PublicIncreaseDepthV3ApiItem, PublicIncreaseDepthV3ApiItemJson> = /*@__PURE__*/
  messageDesc(file_PublicIncreaseDepthsV3Api, 1);

