// spot@public.deals.v3.api.pb

// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,json_types=true"
// @generated from file PublicDealsV3Api.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PublicDealsV3Api.proto.
 */
export const file_PublicDealsV3Api: GenFile = /*@__PURE__*/
  fileDesc("ChZQdWJsaWNEZWFsc1YzQXBpLnByb3RvIksKEFB1YmxpY0RlYWxzVjNBcGkSJAoFZGVhbHMYASADKAsyFS5QdWJsaWNEZWFsc1YzQXBpSXRlbRIRCglldmVudFR5cGUYAiABKAkiWAoUUHVibGljRGVhbHNWM0FwaUl0ZW0SDQoFcHJpY2UYASABKAkSEAoIcXVhbnRpdHkYAiABKAkSEQoJdHJhZGVUeXBlGAMgASgFEgwKBHRpbWUYBCABKANCOQocY29tLm14Yy5wdXNoLmNvbW1vbi5wcm90b2J1ZkIVUHVibGljRGVhbHNWM0FwaVByb3RvSAFQAWIGcHJvdG8z");

/**
 * @generated from message PublicDealsV3Api
 */
export type PublicDealsV3Api = Message<"PublicDealsV3Api"> & {
  /**
   * @generated from field: repeated PublicDealsV3ApiItem deals = 1;
   */
  deals: PublicDealsV3ApiItem[];

  /**
   * @generated from field: string eventType = 2;
   */
  eventType: string;
};

/**
 * @generated from message PublicDealsV3Api
 */
export type PublicDealsV3ApiJson = {
  /**
   * @generated from field: repeated PublicDealsV3ApiItem deals = 1;
   */
  deals?: PublicDealsV3ApiItemJson[];

  /**
   * @generated from field: string eventType = 2;
   */
  eventType?: string;
};

/**
 * Describes the message PublicDealsV3Api.
 * Use `create(PublicDealsV3ApiSchema)` to create a new message.
 */
export const PublicDealsV3ApiSchema: GenMessage<PublicDealsV3Api, PublicDealsV3ApiJson> = /*@__PURE__*/
  messageDesc(file_PublicDealsV3Api, 0);

/**
 * @generated from message PublicDealsV3ApiItem
 */
export type PublicDealsV3ApiItem = Message<"PublicDealsV3ApiItem"> & {
  /**
   * @generated from field: string price = 1;
   */
  price: string;

  /**
   * @generated from field: string quantity = 2;
   */
  quantity: string;

  /**
   * @generated from field: int32 tradeType = 3;
   */
  tradeType: number;

  /**
   * @generated from field: int64 time = 4;
   */
  time: bigint;
};

/**
 * @generated from message PublicDealsV3ApiItem
 */
export type PublicDealsV3ApiItemJson = {
  /**
   * @generated from field: string price = 1;
   */
  price?: string;

  /**
   * @generated from field: string quantity = 2;
   */
  quantity?: string;

  /**
   * @generated from field: int32 tradeType = 3;
   */
  tradeType?: number;

  /**
   * @generated from field: int64 time = 4;
   */
  time?: string;
};

/**
 * Describes the message PublicDealsV3ApiItem.
 * Use `create(PublicDealsV3ApiItemSchema)` to create a new message.
 */
export const PublicDealsV3ApiItemSchema: GenMessage<PublicDealsV3ApiItem, PublicDealsV3ApiItemJson> = /*@__PURE__*/
  messageDesc(file_PublicDealsV3Api, 1);

