// spot@public.increase.depth.v3.api.pb

// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,json_types=true"
// @generated from file PublicIncreaseDepthsBatchV3Api.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { PublicIncreaseDepthsV3Api, PublicIncreaseDepthsV3ApiJson } from "./PublicIncreaseDepthsV3Api_pb";
import { file_PublicIncreaseDepthsV3Api } from "./PublicIncreaseDepthsV3Api_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PublicIncreaseDepthsBatchV3Api.proto.
 */
export const file_PublicIncreaseDepthsBatchV3Api: GenFile = /*@__PURE__*/
  fileDesc("CiRQdWJsaWNJbmNyZWFzZURlcHRoc0JhdGNoVjNBcGkucHJvdG8iXgoeUHVibGljSW5jcmVhc2VEZXB0aHNCYXRjaFYzQXBpEikKBWl0ZW1zGAEgAygLMhouUHVibGljSW5jcmVhc2VEZXB0aHNWM0FwaRIRCglldmVudFR5cGUYAiABKAlCRwocY29tLm14Yy5wdXNoLmNvbW1vbi5wcm90b2J1ZkIjUHVibGljSW5jcmVhc2VEZXB0aHNCYXRjaFYzQXBpUHJvdG9IAVABYgZwcm90bzM", [file_PublicIncreaseDepthsV3Api]);

/**
 * @generated from message PublicIncreaseDepthsBatchV3Api
 */
export type PublicIncreaseDepthsBatchV3Api = Message<"PublicIncreaseDepthsBatchV3Api"> & {
  /**
   * @generated from field: repeated PublicIncreaseDepthsV3Api items = 1;
   */
  items: PublicIncreaseDepthsV3Api[];

  /**
   * @generated from field: string eventType = 2;
   */
  eventType: string;
};

/**
 * @generated from message PublicIncreaseDepthsBatchV3Api
 */
export type PublicIncreaseDepthsBatchV3ApiJson = {
  /**
   * @generated from field: repeated PublicIncreaseDepthsV3Api items = 1;
   */
  items?: PublicIncreaseDepthsV3ApiJson[];

  /**
   * @generated from field: string eventType = 2;
   */
  eventType?: string;
};

/**
 * Describes the message PublicIncreaseDepthsBatchV3Api.
 * Use `create(PublicIncreaseDepthsBatchV3ApiSchema)` to create a new message.
 */
export const PublicIncreaseDepthsBatchV3ApiSchema: GenMessage<PublicIncreaseDepthsBatchV3Api, PublicIncreaseDepthsBatchV3ApiJson> = /*@__PURE__*/
  messageDesc(file_PublicIncreaseDepthsBatchV3Api, 0);

