// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,json_types=true"
// @generated from file PushDataV3ApiWrapper.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { PublicDealsV3Api, PublicDealsV3ApiJson } from "./PublicDealsV3Api_pb";
import { file_PublicDealsV3Api } from "./PublicDealsV3Api_pb";
import type { PublicIncreaseDepthsV3Api, PublicIncreaseDepthsV3ApiJson } from "./PublicIncreaseDepthsV3Api_pb";
import { file_PublicIncreaseDepthsV3Api } from "./PublicIncreaseDepthsV3Api_pb";
import type { PublicLimitDepthsV3Api, PublicLimitDepthsV3ApiJson } from "./PublicLimitDepthsV3Api_pb";
import { file_PublicLimitDepthsV3Api } from "./PublicLimitDepthsV3Api_pb";
import type { PrivateOrdersV3Api, PrivateOrdersV3ApiJson } from "./PrivateOrdersV3Api_pb";
import { file_PrivateOrdersV3Api } from "./PrivateOrdersV3Api_pb";
import type { PublicBookTickerV3Api, PublicBookTickerV3ApiJson } from "./PublicBookTickerV3Api_pb";
import { file_PublicBookTickerV3Api } from "./PublicBookTickerV3Api_pb";
import type { PrivateDealsV3Api, PrivateDealsV3ApiJson } from "./PrivateDealsV3Api_pb";
import { file_PrivateDealsV3Api } from "./PrivateDealsV3Api_pb";
import type { PrivateAccountV3Api, PrivateAccountV3ApiJson } from "./PrivateAccountV3Api_pb";
import { file_PrivateAccountV3Api } from "./PrivateAccountV3Api_pb";
import type { PublicSpotKlineV3Api, PublicSpotKlineV3ApiJson } from "./PublicSpotKlineV3Api_pb";
import { file_PublicSpotKlineV3Api } from "./PublicSpotKlineV3Api_pb";
import type { PublicMiniTickerV3Api, PublicMiniTickerV3ApiJson } from "./PublicMiniTickerV3Api_pb";
import { file_PublicMiniTickerV3Api } from "./PublicMiniTickerV3Api_pb";
import type { PublicMiniTickersV3Api, PublicMiniTickersV3ApiJson } from "./PublicMiniTickersV3Api_pb";
import { file_PublicMiniTickersV3Api } from "./PublicMiniTickersV3Api_pb";
import type { PublicBookTickerBatchV3Api, PublicBookTickerBatchV3ApiJson } from "./PublicBookTickerBatchV3Api_pb";
import { file_PublicBookTickerBatchV3Api } from "./PublicBookTickerBatchV3Api_pb";
import type { PublicIncreaseDepthsBatchV3Api, PublicIncreaseDepthsBatchV3ApiJson } from "./PublicIncreaseDepthsBatchV3Api_pb";
import { file_PublicIncreaseDepthsBatchV3Api } from "./PublicIncreaseDepthsBatchV3Api_pb";
import type { PublicAggreDepthsV3Api, PublicAggreDepthsV3ApiJson } from "./PublicAggreDepthsV3Api_pb";
import { file_PublicAggreDepthsV3Api } from "./PublicAggreDepthsV3Api_pb";
import type { PublicAggreDealsV3Api, PublicAggreDealsV3ApiJson } from "./PublicAggreDealsV3Api_pb";
import { file_PublicAggreDealsV3Api } from "./PublicAggreDealsV3Api_pb";
import type { PublicAggreBookTickerV3Api, PublicAggreBookTickerV3ApiJson } from "./PublicAggreBookTickerV3Api_pb";
import { file_PublicAggreBookTickerV3Api } from "./PublicAggreBookTickerV3Api_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file PushDataV3ApiWrapper.proto.
 */
export const file_PushDataV3ApiWrapper: GenFile = /*@__PURE__*/
  fileDesc("ChpQdXNoRGF0YVYzQXBpV3JhcHBlci5wcm90byLwBwoUUHVzaERhdGFWM0FwaVdyYXBwZXISDwoHY2hhbm5lbBgBIAEoCRIpCgtwdWJsaWNEZWFscxitAiABKAsyES5QdWJsaWNEZWFsc1YzQXBpSAASOwoUcHVibGljSW5jcmVhc2VEZXB0aHMYrgIgASgLMhouUHVibGljSW5jcmVhc2VEZXB0aHNWM0FwaUgAEjUKEXB1YmxpY0xpbWl0RGVwdGhzGK8CIAEoCzIXLlB1YmxpY0xpbWl0RGVwdGhzVjNBcGlIABItCg1wcml2YXRlT3JkZXJzGLACIAEoCzITLlByaXZhdGVPcmRlcnNWM0FwaUgAEjMKEHB1YmxpY0Jvb2tUaWNrZXIYsQIgASgLMhYuUHVibGljQm9va1RpY2tlclYzQXBpSAASKwoMcHJpdmF0ZURlYWxzGLICIAEoCzISLlByaXZhdGVEZWFsc1YzQXBpSAASLwoOcHJpdmF0ZUFjY291bnQYswIgASgLMhQuUHJpdmF0ZUFjY291bnRWM0FwaUgAEjEKD3B1YmxpY1Nwb3RLbGluZRi0AiABKAsyFS5QdWJsaWNTcG90S2xpbmVWM0FwaUgAEjMKEHB1YmxpY01pbmlUaWNrZXIYtQIgASgLMhYuUHVibGljTWluaVRpY2tlclYzQXBpSAASNQoRcHVibGljTWluaVRpY2tlcnMYtgIgASgLMhcuUHVibGljTWluaVRpY2tlcnNWM0FwaUgAEj0KFXB1YmxpY0Jvb2tUaWNrZXJCYXRjaBi3AiABKAsyGy5QdWJsaWNCb29rVGlja2VyQmF0Y2hWM0FwaUgAEkUKGXB1YmxpY0luY3JlYXNlRGVwdGhzQmF0Y2gYuAIgASgLMh8uUHVibGljSW5jcmVhc2VEZXB0aHNCYXRjaFYzQXBpSAASNQoRcHVibGljQWdncmVEZXB0aHMYuQIgASgLMhcuUHVibGljQWdncmVEZXB0aHNWM0FwaUgAEjMKEHB1YmxpY0FnZ3JlRGVhbHMYugIgASgLMhYuUHVibGljQWdncmVEZWFsc1YzQXBpSAASPQoVcHVibGljQWdncmVCb29rVGlja2VyGLsCIAEoCzIbLlB1YmxpY0FnZ3JlQm9va1RpY2tlclYzQXBpSAASEwoGc3ltYm9sGAMgASgJSAGIAQESFQoIc3ltYm9sSWQYBCABKAlIAogBARIXCgpjcmVhdGVUaW1lGAUgASgDSAOIAQESFQoIc2VuZFRpbWUYBiABKANIBIgBAUIGCgRib2R5QgkKB19zeW1ib2xCCwoJX3N5bWJvbElkQg0KC19jcmVhdGVUaW1lQgsKCV9zZW5kVGltZUI9Chxjb20ubXhjLnB1c2guY29tbW9uLnByb3RvYnVmQhlQdXNoRGF0YVYzQXBpV3JhcHBlclByb3RvSAFQAWIGcHJvdG8z", [file_PublicDealsV3Api, file_PublicIncreaseDepthsV3Api, file_PublicLimitDepthsV3Api, file_PrivateOrdersV3Api, file_PublicBookTickerV3Api, file_PrivateDealsV3Api, file_PrivateAccountV3Api, file_PublicSpotKlineV3Api, file_PublicMiniTickerV3Api, file_PublicMiniTickersV3Api, file_PublicBookTickerBatchV3Api, file_PublicIncreaseDepthsBatchV3Api, file_PublicAggreDepthsV3Api, file_PublicAggreDealsV3Api, file_PublicAggreBookTickerV3Api]);

/**
 * @generated from message PushDataV3ApiWrapper
 */
export type PushDataV3ApiWrapper = Message<"PushDataV3ApiWrapper"> & {
  /**
   * *
   * 频道
   *
   * @generated from field: string channel = 1;
   */
  channel: string;

  /**
   * *
   * 数据，NOTE：因为不能重复，所以类型和变量名尽量使用全名
   *
   * @generated from oneof PushDataV3ApiWrapper.body
   */
  body: {
    /**
     * @generated from field: PublicDealsV3Api publicDeals = 301;
     */
    value: PublicDealsV3Api;
    case: "publicDeals";
  } | {
    /**
     * @generated from field: PublicIncreaseDepthsV3Api publicIncreaseDepths = 302;
     */
    value: PublicIncreaseDepthsV3Api;
    case: "publicIncreaseDepths";
  } | {
    /**
     * @generated from field: PublicLimitDepthsV3Api publicLimitDepths = 303;
     */
    value: PublicLimitDepthsV3Api;
    case: "publicLimitDepths";
  } | {
    /**
     * @generated from field: PrivateOrdersV3Api privateOrders = 304;
     */
    value: PrivateOrdersV3Api;
    case: "privateOrders";
  } | {
    /**
     * @generated from field: PublicBookTickerV3Api publicBookTicker = 305;
     */
    value: PublicBookTickerV3Api;
    case: "publicBookTicker";
  } | {
    /**
     * @generated from field: PrivateDealsV3Api privateDeals = 306;
     */
    value: PrivateDealsV3Api;
    case: "privateDeals";
  } | {
    /**
     * @generated from field: PrivateAccountV3Api privateAccount = 307;
     */
    value: PrivateAccountV3Api;
    case: "privateAccount";
  } | {
    /**
     * @generated from field: PublicSpotKlineV3Api publicSpotKline = 308;
     */
    value: PublicSpotKlineV3Api;
    case: "publicSpotKline";
  } | {
    /**
     * @generated from field: PublicMiniTickerV3Api publicMiniTicker = 309;
     */
    value: PublicMiniTickerV3Api;
    case: "publicMiniTicker";
  } | {
    /**
     * @generated from field: PublicMiniTickersV3Api publicMiniTickers = 310;
     */
    value: PublicMiniTickersV3Api;
    case: "publicMiniTickers";
  } | {
    /**
     * @generated from field: PublicBookTickerBatchV3Api publicBookTickerBatch = 311;
     */
    value: PublicBookTickerBatchV3Api;
    case: "publicBookTickerBatch";
  } | {
    /**
     * @generated from field: PublicIncreaseDepthsBatchV3Api publicIncreaseDepthsBatch = 312;
     */
    value: PublicIncreaseDepthsBatchV3Api;
    case: "publicIncreaseDepthsBatch";
  } | {
    /**
     * @generated from field: PublicAggreDepthsV3Api publicAggreDepths = 313;
     */
    value: PublicAggreDepthsV3Api;
    case: "publicAggreDepths";
  } | {
    /**
     * @generated from field: PublicAggreDealsV3Api publicAggreDeals = 314;
     */
    value: PublicAggreDealsV3Api;
    case: "publicAggreDeals";
  } | {
    /**
     * @generated from field: PublicAggreBookTickerV3Api publicAggreBookTicker = 315;
     */
    value: PublicAggreBookTickerV3Api;
    case: "publicAggreBookTicker";
  } | { case: undefined; value?: undefined };

  /**
   * *
   * 交易对
   *
   * @generated from field: optional string symbol = 3;
   */
  symbol?: string;

  /**
   * *
   * 交易对ID
   *
   * @generated from field: optional string symbolId = 4;
   */
  symbolId?: string;

  /**
   * *
   * 消息生成时间
   *
   * @generated from field: optional int64 createTime = 5;
   */
  createTime?: bigint;

  /**
   * *
   * 消息推送时间
   *
   * @generated from field: optional int64 sendTime = 6;
   */
  sendTime?: bigint;
};

/**
 * @generated from message PushDataV3ApiWrapper
 */
export type PushDataV3ApiWrapperJson = {
  /**
   * *
   * 频道
   *
   * @generated from field: string channel = 1;
   */
  channel?: string;

  /**
   * @generated from field: PublicDealsV3Api publicDeals = 301;
   */
  publicDeals?: PublicDealsV3ApiJson;

  /**
   * @generated from field: PublicIncreaseDepthsV3Api publicIncreaseDepths = 302;
   */
  publicIncreaseDepths?: PublicIncreaseDepthsV3ApiJson;

  /**
   * @generated from field: PublicLimitDepthsV3Api publicLimitDepths = 303;
   */
  publicLimitDepths?: PublicLimitDepthsV3ApiJson;

  /**
   * @generated from field: PrivateOrdersV3Api privateOrders = 304;
   */
  privateOrders?: PrivateOrdersV3ApiJson;

  /**
   * @generated from field: PublicBookTickerV3Api publicBookTicker = 305;
   */
  publicBookTicker?: PublicBookTickerV3ApiJson;

  /**
   * @generated from field: PrivateDealsV3Api privateDeals = 306;
   */
  privateDeals?: PrivateDealsV3ApiJson;

  /**
   * @generated from field: PrivateAccountV3Api privateAccount = 307;
   */
  privateAccount?: PrivateAccountV3ApiJson;

  /**
   * @generated from field: PublicSpotKlineV3Api publicSpotKline = 308;
   */
  publicSpotKline?: PublicSpotKlineV3ApiJson;

  /**
   * @generated from field: PublicMiniTickerV3Api publicMiniTicker = 309;
   */
  publicMiniTicker?: PublicMiniTickerV3ApiJson;

  /**
   * @generated from field: PublicMiniTickersV3Api publicMiniTickers = 310;
   */
  publicMiniTickers?: PublicMiniTickersV3ApiJson;

  /**
   * @generated from field: PublicBookTickerBatchV3Api publicBookTickerBatch = 311;
   */
  publicBookTickerBatch?: PublicBookTickerBatchV3ApiJson;

  /**
   * @generated from field: PublicIncreaseDepthsBatchV3Api publicIncreaseDepthsBatch = 312;
   */
  publicIncreaseDepthsBatch?: PublicIncreaseDepthsBatchV3ApiJson;

  /**
   * @generated from field: PublicAggreDepthsV3Api publicAggreDepths = 313;
   */
  publicAggreDepths?: PublicAggreDepthsV3ApiJson;

  /**
   * @generated from field: PublicAggreDealsV3Api publicAggreDeals = 314;
   */
  publicAggreDeals?: PublicAggreDealsV3ApiJson;

  /**
   * @generated from field: PublicAggreBookTickerV3Api publicAggreBookTicker = 315;
   */
  publicAggreBookTicker?: PublicAggreBookTickerV3ApiJson;

  /**
   * *
   * 交易对
   *
   * @generated from field: optional string symbol = 3;
   */
  symbol?: string;

  /**
   * *
   * 交易对ID
   *
   * @generated from field: optional string symbolId = 4;
   */
  symbolId?: string;

  /**
   * *
   * 消息生成时间
   *
   * @generated from field: optional int64 createTime = 5;
   */
  createTime?: string;

  /**
   * *
   * 消息推送时间
   *
   * @generated from field: optional int64 sendTime = 6;
   */
  sendTime?: string;
};

/**
 * Describes the message PushDataV3ApiWrapper.
 * Use `create(PushDataV3ApiWrapperSchema)` to create a new message.
 */
export const PushDataV3ApiWrapperSchema: GenMessage<PushDataV3ApiWrapper, PushDataV3ApiWrapperJson> = /*@__PURE__*/
  messageDesc(file_PushDataV3ApiWrapper, 0);

